#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#  this is good bin to clean dirty playground!
cleanCase
rm -rf machineA
rm -rf machineB

#------------------------------------------------------------------------------
