#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
#runApplication blockMesh
#  rm log.wr-blockMesh
runApplication wr-blockMesh
#  runApplication blockMesh
runApplication icoFoam

#------------------------------------------------------------------------------
